# Netlify configuration for Blaze Intelligence
# Security headers, caching, and redirects. SPA fallback is provided (commented).

# Force HTTPS (domain-level)
[[redirects]]
  from = "http://blaze-intelligence.netlify.app/*"
  to = "https://blaze-intelligence.netlify.app/:splat"
  status = 301
  force = true

# API Routes
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
  force = true

# Fix broken navigation links
[[redirects]]
  from = "/nil-calculator-advanced"
  to = "/nil-valuation.html"
  status = 301

[[redirects]]
  from = "/sports-intelligence-dashboard"
  to = "/sports-intelligence.html"
  status = 301

[[redirects]]
  from = "/ar-coaching-platform"
  to = "/ar-coaching.html"
  status = 301

[[redirects]]
  from = "/character-assessment"
  to = "/character-assessment.html"
  status = 301

[[redirects]]
  from = "/contact"
  to = "/resources/contact.html"
  status = 200

# --- Global Security Headers ---
[[headers]]
  for = "/*"
  [headers.values]
    Strict-Transport-Security = "max-age=63072000; includeSubDomains; preload"
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "DENY"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "accelerometer=(), camera=(), geolocation=(), gyroscope=(), microphone=(), midi=(), payment=()"
    Content-Security-Policy = "default-src 'self'; img-src 'self' data: https:; font-src 'self' https: data:; style-src 'self' 'unsafe-inline' https:; script-src 'self' 'unsafe-inline' https:; connect-src 'self' https: wss:; frame-ancestors 'none'; base-uri 'self'; form-action 'self' https://*.netlify.app https://*.netlify.com;"

# --- Caching ---
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/js/*.js"
  [headers.values]
    Cache-Control = "public, max-age=604800, immutable"

[[headers]]
  for = "/css/*.css"
  [headers.values]
    Cache-Control = "public, max-age=604800, immutable"

[[headers]]
  for = "/*.html"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

[build.environment]
  NODE_ENV = "production"
  BLAZE_ENVIRONMENT = "production"
