[[redirects]]
# Redirect legacy or broken paths to their new equivalents. This helps avoid 404s
# for visitors who have bookmarked old URLs or clicked outdated links.
# Each redirect uses a 200 (OK) status so the browser doesn’t change the URL,
# allowing single‑page apps to handle navigation internally if desired.
from = "/blaze-championship-live"
to   = "/index.html"
status = 200

[[redirects]]
from = "/index-championship-ultimate"
to   = "/analytics.html"
status = 200

[[redirects]]
from = "/championship-3d-universe"
to   = "/universe.html"
status = 200

[[redirects]]
from = "/championship-ai-analytics"
to   = "/analytics.html"
status = 200

# Redirect legacy contact and demo paths to new pages
[[redirects]]
from = "/contact"
to   = "/contact.html"
status = 200

[[redirects]]
from = "/demo"
to   = "/demo.html"
status = 200

# Provide clean extensionless URLs for analytics and universe
[[redirects]]
from = "/analytics"
to   = "/analytics.html"
status = 200

[[redirects]]
from = "/universe"
to   = "/universe.html"
status = 200

# Security headers with CSP allowing Three.js and external resources
[[headers]]
for = "/*"
  [headers.values]
  X-Frame-Options = "DENY"
  X-XSS-Protection = "1; mode=block"
  X-Content-Type-Options = "nosniff"
  Referrer-Policy = "strict-origin-when-cross-origin"
  Content-Security-Policy = "script-src 'self' 'unsafe-inline' 'unsafe-eval' https://js.stripe.com https://cdnjs.cloudflare.com https://cdn.jsdelivr.net https://unpkg.com; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; font-src 'self' https://fonts.gstatic.com; img-src 'self' data: https: blob:; connect-src 'self' https: wss:; object-src 'none'; base-uri 'self'"

# Proper MIME types for JavaScript files
[[headers]]
for = "/*.js"
  [headers.values]
  Content-Type = "application/javascript; charset=utf-8"
  Cache-Control = "public, max-age=31536000, immutable"

# CSS file headers
[[headers]]
for = "/*.css"
  [headers.values]
  Content-Type = "text/css; charset=utf-8"
  Cache-Control = "public, max-age=31536000, immutable"