[build]
  command = "npm run build:unified || echo 'Unified platform ready'"
  publish = "."
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "18"
  BLAZE_ENV = "production"
  MCP_SERVER_URL = "https://blaze-intelligence-mcp.onrender.com"
  CHAMPIONSHIP_MODE = "true"
  REAL_TIME_UPDATES = "true"

# Headers for security and caching
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"

[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/images/*"
  [headers.values]
    Cache-Control = "public, max-age=604800, immutable"

# MCP Server Integration Headers
[[headers]]
  for = "/mcp/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type, Authorization, mcp-session-id"
    Access-Control-Expose-Headers = "Mcp-Session-Id"
    Access-Control-Max-Age = "86400"
    X-Powered-By = "Blaze-Intelligence-MCP"
    X-Sports-Analytics = "Championship-Platform"

# API redirects for Hawk-Eye endpoints
[[redirects]]
  from = "/api/mcp-proxy"
  to = "/.netlify/functions/hawkeye-mcp-proxy"
  status = 200
  force = true

[[redirects]]
  from = "/api/hawkeye/track"
  to = "/.netlify/functions/hawkeye-track"
  status = 200
  force = true

[[redirects]]
  from = "/api/hawkeye/predict"
  to = "/.netlify/functions/hawkeye-predict"
  status = 200
  force = true

[[redirects]]
  from = "/api/hawkeye/strike-zone"
  to = "/.netlify/functions/hawkeye-strike-zone"
  status = 200
  force = true

# Sports Data API
[[redirects]]
  from = "/api/sports/*"
  to = "/.netlify/functions/sports-data-api"
  status = 200
  force = true

# SportsDataIO API
[[redirects]]
  from = "/api/sportsdataio/*"
  to = "/.netlify/functions/sportsdataio-api"
  status = 200
  force = true

# Texas High School Football API
[[redirects]]
  from = "/api/texas-hs-football"
  to = "/.netlify/functions/texas-hs-football"
  status = 200
  force = true

# SEC/Texas Baseball API
[[redirects]]
  from = "/api/sec-tx-baseball"
  to = "/.netlify/functions/sec-tx-baseball"
  status = 200
  force = true

# MCP Server Proxy
[[redirects]]
  from = "/mcp/*"
  to = "/.netlify/functions/hawkeye-mcp-proxy"
  status = 200

# General API redirect
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# Legacy redirects
[[redirects]]
  from = "/blaze-3d-universe.html"
  to = "/universe.html"
  status = 301
  force = true

[[redirects]]
  from = "/nil-calculator"
  to = "/sec-nil-analytics.html"
  status = 301
  force = true

# WebSocket support (Edge function required for production)
[[edge_functions]]
  path = "/ws/*"
  function = "websocket-handler"