# Blaze Intelligence - Southern Sports Authority Platform
# Netlify Configuration for Multi-Site Deployment

[build]
  publish = "dist"
  command = "npm run build:unified"

[build.environment]
  NODE_VERSION = "22"
  BLAZE_PRIMARY_URL = "https://blaze-intelligence.netlify.app"
  BLAZE_ANALYTICS_URL = "https://blaze-intelligence-main.netlify.app"
  BLAZE_3D_URL = "https://blaze-3d.netlify.app"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

# Headers for better performance and security
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "accelerometer=(), camera=(), geolocation=(), gyroscope=(), magnetometer=(), microphone=(), payment=(), usb=()"
    Content-Security-Policy = "default-src 'self' https:; script-src 'self' 'unsafe-inline' 'unsafe-eval' https://cdn.jsdelivr.net https://cdnjs.cloudflare.com https://unpkg.com https://www.googletagmanager.com https://cdn.babylonjs.com https://preview.babylonjs.com; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com https://cdn.jsdelivr.net; font-src 'self' https://fonts.gstatic.com data:; img-src 'self' data: https: blob:; connect-src 'self' https://api.sportsdataio.com https://*.netlify.app wss://*.netlify.app https://blaze-intelligence.netlify.app https://blaze-intelligence-main.netlify.app https://blaze-3d.netlify.app; frame-ancestors 'none'; frame-src 'self' https://blaze-intelligence.netlify.app https://blaze-intelligence-main.netlify.app https://blaze-3d.netlify.app;"
    Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"
    Cross-Origin-Embedder-Policy = "credentialless"
    Cross-Origin-Opener-Policy = "same-origin"
    Cross-Origin-Resource-Policy = "cross-origin"

[[headers]]
  for = "/public/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "/**/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "/**/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

# Main application routes - accessible via clean URLs
[[redirects]]
from = "/app"
to = "/app.html"
status = 200

[[redirects]]
from = "/sports-intelligence"
to = "/public/sports-intelligence.html"
status = 200

[[redirects]]
from = "/pressure-dashboard"
to = "/public/pressure-dashboard.html"
status = 200

[[redirects]]
from = "/analytics"
to = "/public/analytics.html"
status = 200

[[redirects]]
from = "/athlete-dashboard"
to = "/athlete-dashboard.html"
status = 200

[[redirects]]
from = "/manifesto"
to = "/manifesto.html"
status = 200

[[redirects]]
from = "/proof"
to = "/proof.html"
status = 200

# Additional public pages
[[redirects]]
from = "/neural-coach"
to = "/public/neural-coach.html"
status = 200

[[redirects]]
from = "/digital-combine"
to = "/public/digital-combine.html"
status = 200

[[redirects]]
from = "/nil"
to = "/public/nil.html"
status = 200

[[redirects]]
from = "/live-demo"
to = "/public/live-demo.html"
status = 200

[[redirects]]
from = "/enterprise-services"
to = "/public/enterprise-services.html"
status = 200

# Legacy redirects for backward compatibility
[[redirects]]
from = "/blaze-championship-live"
to = "/index.html"
status = 301

[[redirects]]
from = "/index-championship-ultimate"
to = "/public/analytics.html"
status = 301

[[redirects]]
from = "/championship-3d-universe"
to = "/public/sports-intelligence.html"
status = 301

[[redirects]]
from = "/championship-ai-analytics"
to = "/public/analytics.html"
status = 301

# Domain redirects from other Netlify sites
[[redirects]]
from = "https://blaze-intelligence-main.netlify.app/*"
to = "https://blaze-intelligence.netlify.app/unified-platform-hub.html"
status = 301
force = true

[[redirects]]
from = "https://blaze-3d.netlify.app/*"
to = "https://blaze-intelligence.netlify.app/unified-platform-hub.html"
status = 301
force = true

# Unified Platform Hub Access Points
[[redirects]]
from = "/hub"
to = "/unified-platform-hub.html"
status = 200

[[redirects]]
from = "/platform"
to = "/unified-platform-hub.html"
status = 200

[[redirects]]
from = "/platforms"
to = "/unified-platform-hub.html"
status = 200

# Platform-specific redirects
[[redirects]]
from = "/platform/main"
to = "/index.html"
status = 200

[[redirects]]
from = "/platform/rti"
to = "/rti-multimodal-dashboard.html"
status = 200

[[redirects]]
from = "/platform/3d"
to = "/blaze-3d-universe.html"
status = 200

# External platform redirects
[[redirects]]
from = "/analytics-hub"
to = "https://blaze-intelligence-main.netlify.app/"
status = 301
force = true

[[redirects]]
from = "/3d-universe"
to = "https://blaze-3d.netlify.app/"
status = 301
force = true

# API routes for server-side functionality
[[redirects]]
from = "/api/*"
to = "/.netlify/functions/:splat"
status = 200

# Default catch-all - send everything else to index
[[redirects]]
from = "/*"
to = "/index.html"
status = 200